# Generated by Django 4.2 on 2024-03-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('triger', models.TextField(blank=True, verbose_name='тригер')),
                ('period', models.IntegerField(verbose_name='Периодичность')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date_on', models.DateTimeField(verbose_name='Дата вкл')),
                ('date_off', models.DateTimeField(verbose_name='Дата выкл')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
