# Generated by Django 4.2 on 2024-03-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_create',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
